### ISSUE TITLE
[FEATURE] Docker Healthchecks

### ISSUE THREAD

**Issue by alx-xlx** [Cleanuparr/Cleanuparr#163]
### What would you like to see implemented next?

I wish cleanuperr has **docker healthchecks** implemented. This is very helpful for tracking the health of container.

https://docs.docker.com/reference/dockerfile/#healthcheck

**Comment by Flaminel** [comment]
I did not implement it directly in the Docker image, but check out the docs and let me know if that's good enough:
https://cleanuparr.github.io/Cleanuparr/docs/configuration/health-checks/
These are available in `v2.0.4`.

**Comment by krohrbaugh** [comment]
My understanding is that, in order to use the health check endpoint recently added with Docker, we'll need `curl` available in the Docker image, since the command [runs within the container](https://docs.docker.com/reference/compose-file/services/#healthcheck), using the default shell (`/bin/sh`).

It doesn't look like it's available as of `v2.0.7`.

```
$ docker exec -i -t cleanuparr sh
# which curl
#
```

Once `curl` is available, we should be able to do:

```
cleanuparr:
  # other container config . . .
  healthcheck:
      test: "curl -f http://localhost:11011/health || exit 1"
      interval: 60s
      timeout: 10s
      retries: 2
```
